
name: Build and deploy native image

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZ_FUNCTION_NAME_APP: mcons    # set this to your application's name

jobs:
    build-and-deploy:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Install GraalVM
              uses: DeLaGuardo/setup-graalvm@3.0
              with:
                graalvm-version: '21.0.0.java11'
            - name: Cache local Maven repository
              uses: actions/cache@v2
              with:
                path: ~/.m2/repository
                key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                restore-keys: |
                  ${{ runner.os }}-maven-
            - name: Test GraalVM installation
              run: java -version
            - name: Install native-image
              run: |
                echo 
                gu install native-image
                ls -a
            - name: Build native image
              run: ./build.sh
            - name: 'Deploy to Azure Function'
              uses: Azure/functions-action@v1
              id: fa
              with:
                app-name: ${{ env.AZ_FUNCTION_NAME_APP }}
                package: target/native_spring_function.zip
                publish-profile: ${{ secrets.SCM_CREDENTIALS_MCONS }}